### PR TITLE
fix!: TextNode text property is not decoded (fixes #134)

### LINKED ISSUE #134: TextNode text property is not decoded
Current node convention is for `rawText` to be the raw, html-encoded text. The `text` property, however, should be html-decoded.

`HtmlNode#text` returns decoded text, however `TextNode#text` simply returns the same as `rawText`.

PR Incoming.

### PR DESCRIPTION
**Pull request by nonara**
## Addressed

1. `TextNode#Text` now is html-decoded
2. `HtmlNode#structuredText` now uses html-decoded text
3. Added trimmed text cache invalidation on `rawText` update (ensures up to date after `HtmlNode#removeWhitespace` is called)

## Notes

- I assume `structuredText` should not preserve html entities, if I'm wrong, let me know and I'll adjust.
- ⚠️ You will want to _**bump major version**_ with this release, as it's likely that someone's code (erroneously) relies on using `text` instead of the proper `rawText` to get html entities

## Associated Issue
https://github.com/crosstype/node-html-markdown/issues/14

### CODE REVIEW

**Comment by nonara** [comment]
Updating tests now...

**Comment by nonara** [comment]
All set

**Comment by taoqf** [comment]
Thanks for your work. based on your pr, I digged it up. please check the code https://github.com/taoqf/node-html-parser/commit/840ffdada195b15b3902135c3635d6f6daf90361 if you have time. 
Let me know if I missed anything.

**Comment by nonara** [comment]
Hi. Unfortunately, there are a few issues.

Principally, according to [spec](http://help.dottoro.com/ljermebq.php) `TextNode#textContent` should be the raw content.

## An appeal

As for this proposal, please consider the following:

- Each node has `text` and `rawText` property
- The documentation for `text` claims that it returns the _unescaped_ text
- Regular nodes decode the `text` property and `rawText` provides access to unescaped
- Presently, `TextNode` simply returns rawText for both `text` and `rawText`, which is counterintuitive and goes against the documentation

Because of this, I would classify this as an error, as it's going against established convention setup for nodes as well as its documentation. It also effectively eliminates the purpose for having both properties. 

**Put more simply, why should `text` and `rawText` be different for `HtmlNode` and the same for `TextNode`?** This bypasses the purpose.

So, although it's technically a breaking change, it is one which makes the code do what the documentation and convention says.

## Issue with textContent

The issue with changing `textContent` is that this property is actually present in the HTML DOM spec, which means that this may actually cause breaking changes for people who are using it. This may affect actually affect even more people.

If you absolutely do not want to change the `text` field, my recommendation is to simply add a new property or to ignore it entirely, and I'll workaround on my end, but I hope I can persuade otherwise.

## Next steps

I would advise removing the current commit, for now, as aside from the notes I put, it has some issues with the tests. 

I will make corrections here, based on your commit. You also have access to commit to this PR as well, so you can ultimately fix what you need to at the end.

File: src/nodes/html.ts [hunk 1]
```diff
@@ -458,7 +458,7 @@ export default class HTMLElement extends Node {
 				if ((node as TextNode).isWhitespace) {
 					return;
 				}
-				node.rawText = (<TextNode>node).trimmedText;
+				node.rawText = (<TextNode>node).trimmedRawText;
```
Comment (nonara) [inline src/nodes/html.ts:461]: Because we are setting `rawText`, we want to be certain that it uses the raw version

File: src/nodes/text.ts [hunk 2]
```diff
@@ -1,14 +1,17 @@
...
 
 /**
  * TextNode to contain a text element in DOM tree.
  * @param {string} value [description]
  */
 export default class TextNode extends Node {
-	public constructor(public rawText: string, parentNode: HTMLElement) {
+	public constructor(rawText: string, parentNode: HTMLElement) {
 		super(parentNode);
+		this._rawText = rawText;
```
Comment (nonara) [inline src/nodes/text.ts:14]: This change allows use to automatically reset trimmed text caches on update

File: src/nodes/text.ts [hunk 3]
```diff
@@ -17,42 +20,38 @@ export default class TextNode extends Node {
...
+	}
+
+	/**
+	 * Set rawText and invalidate trimmed caches
+	 */
+	public set rawText(text: string) {
+		this._rawText = text;
+		this._trimmedRawText = void 0;
+		this._trimmedText = void 0;
+	}
```
Comment (nonara) [inline src/nodes/text.ts:38]: Reset caches when rawText changed

File: src/nodes/text.ts [hunk 4]
```diff
@@ -61,18 +60,50 @@ export default class TextNode extends Node {
 	 * @return {string} text content
 	 */
 	public get text() {
-		return this.rawText;
+		return decode(this.rawText);
```
Comment (nonara) [inline src/nodes/text.ts:63]: Standardize to convention and documentation

File: src/nodes/text.ts [hunk 5]
```diff
@@ -61,18 +60,50 @@ export default class TextNode extends Node {
...
 	}
 
 	/**
 	 * Detect if the node contains only white space.
-	 * @return {bool}
+	 * @return {boolean}
```
Comment (nonara) [inline src/nodes/text.ts:68]: This produced an eslint error, so I updated it

File: test/html.js [hunk 6]
```diff
@@ -198,11 +198,11 @@ describe('HTML Parser', function () {
...
 			it('should remove whitespaces while preserving nodes with content', function () {
-				const root = parseHTML('<p> \r \n  \t <h5>  123  </h5></p>');
+				const root = parseHTML('<p> \r \n  \t <h5>  123&nbsp;  </h5></p>');
 
-				const textNode = new TextNode('  123  ');
-				textNode.rawText = textNode.trimmedText;
-				textNode.rawText.should.eql(' 123 ');
+				const textNode = new TextNode('  123&nbsp;  ');
+				textNode.rawText = textNode.trimmedRawText;
+				textNode.rawText.should.eql(' 123&nbsp; ');
```
Comment (nonara) [inline test/html.js:205]: I wrote this original test in a previous PR. We're altering it slightly to make sure we're using the proper rawText version of trimmed text. We also add in an &nbsp to ensure that it does not decode.

File: src/nodes/text.ts [hunk 7]
```diff
@@ -61,18 +60,50 @@ export default class TextNode extends Node {
...
 	 */
 	public get isWhitespace() {
 		return /^(\s|&nbsp;)*$/.test(this.rawText);
 	}
 
 	public toString() {
-		return this.text;
+		return this.rawText;
+	}
```
Comment (nonara) [inline src/nodes/text.ts:76]: Necessary to ensure `toString` does not decode (as it did not before)

File: test/html.js [hunk 8]
```diff
@@ -415,26 +415,32 @@ describe('HTML Parser', function () {
...
+				const content = `&lt;p&gt; Not a p tag &lt;br /&gt; at all`;
+				const root = parseHTML(`<div>${content}</div>`);
+				root.childNodes.should.have.length(1);
+
+				const divNode = root.firstChild;
+				divNode.childNodes.should.have.length(1);
+
+				const textNode = divNode.firstChild;
+				textNode.rawText.should.eql(content);
+			});
```
Comment (nonara) [inline test/html.js:430]: This test ultimately did not need to be rewritten, however, I left my change in because it is more complete and easier to read. I also renamed it so that it is easier to understand what's happening. If you'd prefer, it can be changed back.

File: test/html.js [hunk 9]
```diff
@@ -415,26 +415,32 @@ describe('HTML Parser', function () {
...
+				const root = parseHTML(`<p>${encodedText}</p>`);
+
+				const pNode = root.firstChild;
+				pNode.text.should.eql(decodedText);
+				pNode.rawText.should.eql(encodedText);
+
+				const textNode = pNode.firstChild;
+				textNode.text.should.eql(decodedText);
+				textNode.rawText.should.eql(encodedText);
 			});
```
Comment (nonara) [inline test/html.js:444]: It made sense to keep this test under the encode/decode heading, as this is core functionality.

**Comment by nonara** [comment]
As a secondary suggestion, I recall your saying you don't have much time for this repo anymore. If you'd like help maintaining it, I'd be happy to come on board.

I currently maintain several large, critical libraries in the parser/compiler space. Because we're looking at a major version bump, I could also go through and clear out some of the issues, clean up the tests, and update them for jest. Let me know if that sounds good.

File: src/nodes/text.ts [hunk 10]
```diff
@@ -1,14 +1,17 @@
...
 /**
  * TextNode to contain a text element in DOM tree.
  * @param {string} value [description]
  */
 export default class TextNode extends Node {
-	public constructor(public rawText: string, parentNode: HTMLElement) {
+	public constructor(rawText: string, parentNode: HTMLElement) {
 		super(parentNode);
+		this._rawText = rawText;
 	}
```
Comment (nonara) [inline src/nodes/text.ts:15]: This change allows us to automatically reset trimmed text caches on update. I added the caching in a previous PR. This change prevents a future bug report with existing code.

**Comment by taoqf** [comment]
Thank you for all your work.

**Comment by taoqf** [comment]
Should I increase the major version? I have not publish new version yet.

**Comment by nonara** [comment]
@taoqf You're very welcome! Thanks for addressing it so quickly! Yes, I would definitely publish as a new major version. 

I'd release as v4.0.0 and add a release with the following notes:

## Breaking Changes

- `TextNode#text` now properly returns HTML decoded text. In order to access the unencoded text, use `TextNode#rawText`
- `HtmlNode#structuredText` is now returning HTML decoded text

**Comment by taoqf** [comment]
https://github.com/taoqf/node-html-parser/releases/tag/v4.0.0
