### PR TITLE
feat: Add range to nodes and fix whitespace issue (fixes #137)

### LINKED ISSUE #137: Cannot determine if whitespace exists between nodes
## Issue

Assuming:

```html
<span>test1</span> <span>test2</span>
<span>test3</span>
<span>test4</span>
```

In browsers, this is rendered as:

---

test1 test2 test3 test4

---

However, it is rendered by the parser as `test1test2test3test4`

The deeper issue is that whitespace between nodes is not being recorded or indicated in any way.

## Solutions

Playing around with this on [astexplorer.net](https://astexplorer.net/) shows that most parsers (ie. htmlparser2, parse5, etc) create a `TextNode` for the whitespace.

What's interesting, however, is that `Angular` takes a more intelligent route, which is likely faster. Like `node-html-parser`, it does not create a `TextNode` for these. Instead, it allows users to determine for themselves via the `range` information attached to each node. 

The `range` information, offered by most parsers, is simply the specific index for where a node begins and ends. Specifically, these positions are for the first char of the opening tag and the last of the closing tag, respectively.

## Proposed solution

I propose simply adding a `range` array to each node, per convention. In so doing, we are able to determine whether a node has trailing whitespace.

For example:
```html
<!-- The following nodes have contiguous ranges. The ranges are [ 0, 17 ] and [ 17, 35 ], respectively. -->
<!-- When we compare the end of the first node (17) with the start of the next (17), we can see there is no space -->
<span>text1</span><span>text2</span>

<!-- These nodes, however are non-contiguous. The ranges are [ 0, 17 ] and [ 18, 37 ], respectively. -->
<!-- By comparing the end and start locations, we know that there is at least one whitespace char between them -->
<span>text1</span>  <span>text2</span>
```

I am submitting a PR shortly.

## Related Issue

https://github.com/crosstype/node-html-markdown/issues/16

### PR DESCRIPTION
**Pull request by nonara**
## Abstract

It turns out that other AST parsers _do_ create a `TextNode` for all whitespace (see https://astexplorer.net) The only which does not is the parser for angular templates, which it likely does because it's used in a very narrow context.

The issue ended up being that `node-html-parser` actually does create a `TextNode` for whitespace, but there were some cases in which that was failing to happen. This caused the behaviour to differ from other parsers and is the root of the issue laid out in #137.

## Features / Fixes

- Added `range` property to nodes
- Fixed whitespace not being created issue (solves #137 & #126)

## Code Changes

- Cleaned up parser code to make it understandable and slightly more efficient
- Added comprehensive test for node ranges
- Added basic whitespace parser test

## Version

*v4.1.0*

Because a feature was added, I recommend bumping minor version.

## Related

- #126
- https://github.com/crosstype/node-html-markdown/issues/16
- #137

### CODE REVIEW

File: src/nodes/html.ts [hunk 1]
```diff
@@ -1012,88 +1018,109 @@ export function base_parse(data: string, options = { lowerCaseTagName: false, co
 			return it.test(tag);
 		});
 	}
-	const root = new HTMLElement(null, {}, '', null);
```
Comment (nonara) [inline src/nodes/html.ts:1015]: I cleaned up the logic a bit, added some comments, and used labels which made it more obvious what's happening. Some efficiency is gained, also.

File: src/nodes/node.ts [hunk 2]
```diff
@@ -8,11 +8,21 @@ import HTMLElement from './html';
...
+	public constructor(
+		public parentNode = null as HTMLElement | null,
+		range?: [ number, number ]
+	) {
+		Object.defineProperty(this, 'range', {
+			enumerable: false,
+			writable: true,
+			configurable: true,
+			value: range ?? [ -1, -1 ]
+		});
```
Comment (nonara) [inline src/nodes/node.ts:25]: We define as non-enumerable, to preserve existing functionality for equality tests between a synthetic node (one created manually) and a parsed node (one created during `parse()`). It's unlikely that this has a broad impact scope outside of this library's own tests, but it seems a good idea to make it non-enumerable anyway. It also allows us to not have to change any of our existing tests to exclude `range` property from equality testing.

File: test/node-ranges.js [hunk 3]
```diff
@@ -0,0 +1,85 @@
+const { parse, HTMLElement, TextNode, CommentNode } = require('../dist');
```
Comment (nonara) [inline test/node-ranges.js:1]: This test parses with `htmlparser2` and compares ranges and nodes. Although it serves as a test for range comparison, it will also be helpful in catching a broad range of other issues with the parser that present tests may not cover. This is because it ensures the AST structures are the same for all fundamental node types (blockText, comment, self-closing, etc) parsed by the parser.

**Comment by nonara** [comment]
@taoqf Ready for review!
